apiVersion: v1
kind: Service
metadata:
  name: cart-svc
  labels:
    app: cart
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3001
      protocol: TCP
  selector:
    app: cart-web-api
