apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cart-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cart-web-api
  template:
    metadata:
      labels:
        app: cart-web-api
    spec:
      containers:
      - name: cart-api-container
        image: nurih/cart-api:0.9.1.1
        env:
          - name: MONGO_URL1
            value: mongodb://mongo-svc:27017/appDemo1
        ports:
        - containerPort: 3001