apiVersion: v1
kind: Pod

metadata:
  name: mongo4
  labels:
    app: cart-microservice
    layer: data
spec:
  containers:
  - name: mongo4-container
    image: mongo:4.0
    ports:
    - containerPort: 27017
